### PR TITLE
storage: do not return empty data set on non-existing metric

### PR DESCRIPTION
**Pull request by jd**
This decision is now available for the upper layer.

### CODE REVIEW

**Comment by jd** [comment]
Fix S3

**Comment by jd** [comment]
Fix 404 handling

**Comment by chungg** [comment]
what's "the upper layer"? it seems better to return 404 if something doesn't exist no?

**Comment by jd** [comment]
> what's "the upper layer"? it seems better to return 404 if something doesn't exist no?

The upper layer is anything that is using it such as the REST API.

Returning 404 would break the API.

**Comment by chungg** [comment]
sorry, i think i'm missing original context but if i ask for a non-existing metric, shouldn't i get 404? this seems to make sense to me.

**Comment by jd** [comment]
That's already the case and this patch does not change this. The REST API checks the existence of metric via the indexer, not via storage.

What this patch changes is that if a metric does not exist in storage, the storage driver does not return `[]` but raises an error. It's really unrelated to the 404 you're talking about.

**Pull request merged**
