### PR TITLE
Don't mock swift for unittests

### PR DESCRIPTION
**Pull request by sileht**

### CODE REVIEW

**Comment by sileht** [comment]
Pull-request updated, HEAD is now 9e8c9949fd1ccd45250dbbbe49fa3f1cb9a24aa8

**Comment by sileht** [comment]
Pull-request updated, HEAD is now 9e8c9949fd1ccd45250dbbbe49fa3f1cb9a24aa8

**Comment by sileht** [comment]
Pull-request updated, HEAD is now d8c0f06279f1e04edf1f117c161b5144894e3f46

**Comment by sileht** [comment]
Pull-request updated, HEAD is now bd5ac72d3080bb917c7c2c671d08c031557c8f4d

**Comment by sileht** [comment]
Pull-request updated, HEAD is now 0553adb80ac9d3d5f84ac8bfefb72e79967b75d5

**Comment by sileht** [comment]
Pull-request updated, HEAD is now 3dcbdee6ff50a34e96e3c01472c825f19341d664

**Comment by sileht** [comment]
Pull-request updated, HEAD is now 95ff49d98bce89858b67c2a8017070e55b1b9661

**Comment by sileht** [comment]
Pull-request updated, HEAD is now aef3cea652447edcf8a3bc52cd283297b3fa3696

**Comment by sileht** [comment]
Pull-request updated, HEAD is now f65c51230bad349d32b05666be36c45b9de74599

**Comment by sileht** [comment]
Pull-request updated, HEAD is now b1f0287268cb7250e682061d7bd9c73e36e2044d

**Comment by sileht** [comment]
Pull-request updated, HEAD is now ef6a5a7da6fd39e126e5f93ee79166b81d5e509c

**Comment by sileht** [comment]
Pull-request updated, HEAD is now 9a312d05bfd4c88f0000f7de8982ca56e0378328

**Comment by sileht** [comment]
Pull-request updated, HEAD is now 5ab3438f93322ed6bae4d33abb6a0a805e04d5c0

**Comment by sileht** [comment]
Pull-request updated, HEAD is now 13899324e9274533c3fdcf0fd0c8934dbe447ae0

**Comment by sileht** [comment]
Pull-request updated, HEAD is now d11a42820f4eda485054e91ebcb95b1274b97f03

**Comment by chungg** [comment]
so close

**Comment by sileht** [comment]
Pull-request updated, HEAD is now a7e4c4200a1f3a087cee7b6995df4ec159e1ba2d

**Comment by sileht** [comment]
Pull-request updated, HEAD is now 364276951d91c17e2da3bce4dadea99fce92e464

**Pull request closed without merging**
