### PR TITLE
Add incoming/indexer/storage information to V1 API's status endpoint

### PR DESCRIPTION
**Pull request by unexceptable**
Rebase of https://github.com/gnocchixyz/gnocchi/pull/995 with fixed for pep8.

### CODE REVIEW

**Comment by Adrian-Turjak** [comment]
@chungg @tobias-urdin I've rebased this myself since it wasn't able to be cleanly done. Plus it looks like @leo-naeka might not be interested in carrying this anymore, so I might take over.

**Comment by Adrian-Turjak** [comment]
the `gnocchi.tests.indexer.sqlalchemy.test_migrations.ModelsMigrationsSync.test_models_sync` failure is unrelated to this, and also failed on master.

So we should fix that and rebase this onto that. Meanwhile will also deal with the comments by @jd in the previous pull request.

**Comment by Adrian-Turjak** [comment]
Getting tests to run locally is proving to be a bit of a pain, but `py37-postgresql-file` is passing locally, so I'm not sure what exactly us causing the 503 failures I'm seeing in travis-ci.

**Comment by jd** [comment]
Some errors seems explicit:
```
    b'      "error": "\'FakeSwiftClient\' object has no attribute \'head_account\'"'
```

**Comment by Adrian-Turjak** [comment]
> Some errors seem explicit:
> 
> ```
>     b'      "error": "\'FakeSwiftClient\' object has no attribute \'head_account\'"'
> ```

Good catch! I've added that now to the FakeSwiftClient, but for now only returning an empty dict. Will have to think about what will be a more appropriate default test return value.

**Comment by Adrian-Turjak** [comment]
@jd Still have a few more of your comments from the other pull request to do, and need to add some more tests, but it's slowly starting to make sense to me. At least this code, and the project itself a little. 

Although gabbi confuses me a little because finding the specific test it ran isn't a simple grep/text search due to the test name in repo appearing differently to the name in the failure. :( It might be worth renaming all the tests with _ rather than spaces to make them easier to search, or I wonder if gabbi has a setting for more verbose test names in failures to make that clearer.

**Comment by jd** [comment]
@cdent might know about Gabbi. Usually, I didn't find those hard to find with a `git grep` and replacing the underscore.

**Comment by cdent** [comment]
> replacing the underscore

That's what I tend to do.

I agree that it's kind of a pain, and an extra step, but there's a conflict between trying to make the yaml files somewhat readable (they are supposed to be as much a thing for humans as for computers) and the demands of `unittest`, `stestr` and other parts of the puzzle.

Certainly if one wanted to rename the `name` values in the gabbi file to use `_` instead of space, that would be an option.

There's another complicating factor: Yesterday lbragstad noticed that when testtools was removed from gabbi, output and logging capture fixtures stopped working. That may make finding and dealing with failures a bit more messy. If that proves to be an issue, downgrading to `gabbi<2.0.0` will fix it until https://github.com/cdent/gabbi/issues/287 is resolved.

**Comment by Adrian-Turjak** [comment]
@cdent I think for me gabbi is weird because I'm used to the python module.class.function path for tests, and gabbi fakes that. Maybe when a test fails it could also print out the relative file path location/test name? Or have a verbosity setting to enable that. 

I found my way around it ultimately, but just felt a little weird for someone who tends to stick with more standard python unit testing.

**Comment by cdent** [comment]
> used to the python module.class.function path for tests

The code that launches the tests is responsible for setting the "faked" name, see https://gabbi.readthedocs.io/en/latest/gabbi.html#gabbi.driver.build_tests

From that it's usually possible to make the test name point to the yaml file, or at least very close.

**Comment by tobias-urdin** [comment]
@mergifyio rebase

**Comment by tobias-urdin** [comment]
@unexceptable Hello 👋 are you still working on this?

**Comment by tobias-urdin** [comment]
Closing, feel free to reopen.

**Pull request closed without merging**
