### PR TITLE
DNM: debug uwsgi

### PR DESCRIPTION
**Pull request by sileht**

### CODE REVIEW

**Comment by sileht** [comment]
Pull-request updated, HEAD is now f9e18bff1ad533976c531781181eab07abf4db25

**Comment by sileht** [comment]
Pull-request updated, HEAD is now dc68366341594c3ca6dca9ca6918fe14af8b0536

**Comment by jd** [comment]
@sileht I've a log that shows that uwsgi receive the kill signal but one of the worker is not killed yet when the new uwsgi starts:

https://api.travis-ci.org/jobs/248805407/log.txt?deansi=true

I think we need to change `--worker-reload-mercy` to 0 or something like that. I did not try yet.

**Comment by sileht** [comment]
My last pifpaf PR should have fix the issue, it sigkill all uwsgi.

**Comment by sileht** [comment]
Also each time swift doesn't work correctly so uswgi i maybe stuck because it can't join swift

**Pull request closed without merging**
