### PR TITLE
aggregates: add rateofchange operator

### PR DESCRIPTION
**Pull request by sileht**

### CODE REVIEW

**Comment by sileht** [comment]
Pull-request updated, HEAD is now 6c94333c36fb2ca755fc43f28c6952d994b4553a

**Comment by jd** [comment]
There seems to be a spurious commit, probably need a rebase.

**Comment by sileht** [comment]
Pull-request updated, HEAD is now 9eab7c50eee0603f94da697fd9afaa733d838bf8

**Comment by sileht** [comment]
Pull-request updated, HEAD is now 009920c828d112a5c12b51c8db763dc80a9f5477

**Pull request merged**
