### PR TITLE
Fix computation for metrics with multiple granularities

### PR DESCRIPTION
**Pull request by openvdro**
The high archive policy created by default contains three different
granularity definitions - 1 second, 1 hour and one day. For such
metrics the split computation has been done incorrectly as it was
using oldest keys not taking into account those keys granularity.
It caused TypeErrors when comparing two SplitKeys with different
granularities.

closes: gnocchixyz/gnocchi#959

### CODE REVIEW

**Comment by openvdro** [comment]
Hey Julien, not very familiar with the code, but I'll try to add something. Current test failures seem to happen because of tenacity though.

**Comment by jd** [comment]
tenacity should be ok now.

**Comment by chungg** [comment]
this probably needs to be backported as well.

**Comment by openvdro** [comment]
yup it also affects 4.3 branch

**Comment by jd** [comment]
Thanks a lot @openvdro !

**Comment by openvdro** [comment]
Hmm, no idea why some tests failed for s3 driver only on postgres

**Comment by openvdro** [comment]
Looking at the failed tests output it almost seems like this call https://github.com/openvdro/gnocchi/blob/master/gnocchi/tests/functional/gabbits/aggregates-with-resources.yaml#L71-L78 did not happen

**Pull request merged**
