### PR TITLE
Fix issue with None value attributes

### PR DESCRIPTION
**Pull request by rafaelweingartner**
With Python 3, the ``sort`` function is not handling `None` values. Therefore, when we handle resources with values as ``None`` an exception happens. This patch fixes such situations.

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
@tobias-urdin this is also an important one. However, its tests will only pass after the following patches have been merged:

- https://github.com/gnocchixyz/gnocchi/pull/1288
- https://github.com/gnocchixyz/gnocchi/pull/1289

**Comment by tobias-urdin** [comment]
Could this be reproduced with a test? I'm trying to understand what the change will do to the grouped data, will there be entries with an empty string? Should those be filtered out instead?

**Comment by rafaelweingartner** [comment]
The code is not designed in a way  that enables us to easily do a unit testing. Let me think about what we can do here.

**Comment by tobias-urdin** [comment]
@mergifyio rebase

**Comment by rafaelweingartner** [comment]
@tobias-urdin I added the unit tests for this one, as you suggested.

**Review by tobias-urdin — APPROVED** [review]

**Comment by tobias-urdin** [comment]
Thanks @rafaelweingartner – let me know if you have anything else you want in master I will cut a 4.5 release sometime this week.

**Pull request merged**
