### PR TITLE
WIP: rest: avoid issue with division by zero

### PR DESCRIPTION
**Pull request by SuderPawel**
Add check to avoid possible issue with division by zero.

From #415.

### CODE REVIEW

**Comment by chungg** [comment]
did you miss a file when you commit? this seems to be exactly same thing you closed?

**Comment by SuderPawel** [comment]
Yeap, I did do sth incorrect in my repo and lost ref to prev pull request. Sorry for inconvenience.

W dniu 12.10.2017, 16:38, o 16:38, użytkownik gord chung <notifications@github.com> napisał:

**Comment by chungg** [comment]
ah, cool cool :)

**Comment by SuderPawel** [comment]
I was trying to reproduce this issue for a long time. Cannot do it. Due to this I am closing it.

**Pull request closed without merging**
