### PR TITLE
metricd: expose respect_processing_delay option

### LINKED ISSUE #507: Redis incoming driver does not respect 'delay' parameter for processing.
### Which version of Gnocchi are you using
4.1

### How to reproduce your problem
The Redis incoming driver should respect the 'delay' processing setting.

### What is the result that you get
The incoming data in Redis is immediately processed even with a non-zero delay

### What is result that you expected
The incoming data would be processed after 'delay' seconds and with a period of 'delay' seconds like the other incoming drivers.

### PR DESCRIPTION
**Pull request by jd**
This allows to disable eager processing of new measures.

Fixes #507

### CODE REVIEW

**Comment by jd** [comment]
Pull-request updated, HEAD is now 34442dc3fe0d37af2326069644bc27eded71fa78

**Comment by chungg** [comment]
i have a slight preference that we make users explicitly enable push rather than explicitly disable push but if everyone else prefers this, i'm ok as well.

**Comment by jd** [comment]
Yeah I really prefer to have push per default. Most users are "complaining" about the delay, not about the eager processing. If you have no scale issue, disabling the notification system is removing a sugar.

**Comment by jd** [comment]
Pull-request updated, HEAD is now 2d78ed3c7254a1f87b35d7ed84bb2442d1d05e52

**Comment by chungg** [comment]
curious, why did you put "complaining" in quotes?

the reason i'd say the opposite is because this makes redis the only driver that behaves differently and it's only in the code that you would be able to figure out redis driver does something unique. it also seems strange to have a parameter to disable something that doesn't exist.

as a secondary, no one has benched this at scale, i'll be honest, the amount of messages this generates i'd be surprised if it actually works at scale.

**Comment by jd** [comment]
> curious, why did you put "complaining" in quotes?

Because it's a more a feature request than a complaint (bug).

> the reason i'd say the opposite is because this makes redis the only driver that behaves differently and it's only in the code that you would be able to figure out redis driver does something unique. it also seems strange to have a parameter to disable something that doesn't exist.

Alright though that sounds more like a documentation issue than a code issue.

> as a secondary, no one has benched this at scale, i'll be honest, the amount of messages this generates i'd be surprised if it actually works at scale.

If your workers are all busy processing a giant sack, then it generates N messages per cycle at max (N = sack numbers), so by default 128 messages over 60 seconds = 2 notif/s. That does not sound like a scalability issue to me.
If you have a worst-case scenario that would show otherwise, please share though.

**Comment by jd** [comment]
@chungg one thing that I can do, though, is renaming this option `respect_processing_delay=False` by `eager_measure_processing=True` (or something like that) if that makes it clearer.

**Comment by chungg** [comment]
> Alright though that sounds more like a documentation issue than a code issue.

for sure. this is the minimum i'd request. we definitely need to highlight this functionality

> If your workers are all busy processing a giant sack, then it generates N messages per cycle at max (N = sack numbers), so by default 128 messages over 60 seconds = 2 notif/s. That does not sound like a scalability issue to me.
> If you have a worst-case scenario that would show otherwise, please share though.

hmm.. as i understand, every single write to redis will generate a MxN messages where M is the number of sacks written to and N is the number of workers. it just happens that the majority of the messages are discarded because it's not relevant to worker or because the worker already knows it needs to process it. so it's really increasing IO (memory) by some factor of MxN.

> `eager_measure_processing=True`

i like this option name... +documentation :)

**Comment by jd** [comment]
> for sure. this is the minimum i'd request. we definitely need to highlight this functionality

Then you should already have opened a documentation issue rather than trying to kill this patch. :)

> hmm.. as i understand, every single write to redis will generate a MxN messages where M is the number of sacks written to and N is the number of workers. it just happens that the majority of the messages are discarded because it's not relevant to worker or because the worker already knows it needs to process it. so it's really increasing IO (memory) by some factor of MxN.

This is true **only if the sack is empty**. If the sack is not empty, not notifications is generated.
So unless your cluster is mostly/often idle, there are actually not that many notifications being generated.

> i like this option name... +documentation :)

Fair enough, I'll add that!

**Comment by chungg** [comment]
uh... now that i think about it. do we want to disable the second write? i guess in theory, it doesn't change much... just whether we care that we are setting a bunch of stale keys constantly for no reason.

**Comment by jd** [comment]
Pull-request updated, HEAD is now 0036fd2eb97655e942c88c6e57dd1604f29c2254

**Comment by jd** [comment]
Pull-request updated, HEAD is now d11045324c521c79f3d4c0f9720898eab0baa558

**Pull request merged**
