### PR TITLE
Fix migrations reusing column objects

### PR DESCRIPTION
**Pull request by Adrian-Turjak**
Closes: https://github.com/gnocchixyz/gnocchi/issues/1080

Related to: https://github.com/sqlalchemy/sqlalchemy/issues/5669

### CODE REVIEW

**Comment by Adrian-Turjak** [comment]
Cool, that seems to have fixed that. :)

**Comment by mrunge** [comment]
Congrats! This looks good to me.

**Review by jd — APPROVED** [review]

**Comment by tobias-urdin** [comment]
@Mergifyio backport stable/4.2

**Comment by tobias-urdin** [comment]
@Mergifyio backport stable/4.4 stable/4.3

**Pull request merged**
