### PR TITLE
Ensure member statistics key is decoded

### PR DESCRIPTION
**Pull request by tobias-urdin**
In the StatusController the statistics for the
members on python3 is a byte string which cannot
be jsonified.

This changes so it loops through the statistics
for the member and ensures the key is a string
and not a byte string.

### CODE REVIEW

**Comment by tobias-urdin** [comment]
@jd @chungg can we merge this as-is? dont know a good way to add tests here

**Review by jd — APPROVED** [review]

**Comment by tobias-urdin** [comment]
@mergifyio backport-to-4.3

**Comment by tobias-urdin** [comment]
@mergifyio backport-stable/4.3

**Comment by tobias-urdin** [comment]
@mergifyio backport stable/4.3

**Pull request merged**
