### PR TITLE
Policy in code requires oslo.policy >= 3.5.0

### PR DESCRIPTION
**Pull request by mrunge**
and thus we should bump the requirement.

### CODE REVIEW

**Review by jd — DISMISSED** [review]

**Comment by tobias-urdin** [comment]
@Mergifyio rebase

**Comment by tobias-urdin** [comment]
lets see with https://github.com/gnocchixyz/gnocchi/pull/1145

**Comment by tobias-urdin** [comment]
@Mergifyio rebase

**Comment by tobias-urdin** [comment]
@Mergifyio rebase

**Pull request merged**
