### PR TITLE
WIP: rest: avoid issue with division by zero

### PR DESCRIPTION
**Pull request by SuderPawel**
Add check to avoid possible issue with division by zero.

/cc @jd

### CODE REVIEW

**Comment by chungg** [comment]
can you a test for this? i imagine the scenario involves somthing where needed_overlap = 0?

**Comment by jd** [comment]
Yes please a test :)

**Comment by SuderPawel** [comment]
@jd, @chungg true.. I missed that thing. :et me do it!

**Comment by SuderPawel** [comment]
Today I tried to clarify what things should be modified/added in [tests](https://github.com/gnocchixyz/gnocchi/blob/master/gnocchi/tests/test_cross_metric.py). Nearly 16 places were found where `aggregated()` function is used. I am considering to have additional test with timeseries with size zero.

What is more, I checked where are other places that something could be divided by zero. There aren't so many places, but I will attach them also.

Would be fine for you? Or anything else?

**Comment by chungg** [comment]
do you know what scenario you did to discover the bug?

this might not be what you saw, but i'm pretty sure you can add a test similar to  https://github.com/gnocchixyz/gnocchi/blob/20f797089b2347024504edda36b05651a3b797a9/gnocchi/tests/test_cross_metric.py#L752-L757

the only thing you need to change is to pass in is a needed_percent_of_overlap=0

again i'm not sure what you did to discover bug :)

**Comment by SuderPawel** [comment]
@chungg what I did to discover that corner scenario was overwriting method [`_get_measures_timeserie()`](https://github.com/gnocchixyz/gnocchi/blob/master/gnocchi/storage/__init__.py#L255) form `StorageDriver`. That private method was overwrite to support some features provided by backend. There was a corner scenario where returned lists with timeseries [here](https://github.com/gnocchixyz/gnocchi/blob/master/gnocchi/rest/cross_metric.py#L108-L112) were empty. Due to that in [`aggregated()`](https://github.com/gnocchixyz/gnocchi/blob/master/gnocchi/rest/cross_metric.py#L119-L120) method `DivisionByZero` was raised :smiley:

**Comment by chungg** [comment]
yeah, i think we're talking about same scenario: empty series and i imagine you have needed_percent_of_overlap=0

there is code that handles empty series but only if overlap is not 0: https://github.com/gnocchixyz/gnocchi/blob/master/gnocchi/rest/cross_metric.py#L154-L155

**Comment by SuderPawel** [comment]
Most propably yes. I will confirm once I will resume my work on that :) 

⁣

W dniu 6.10.2017, 22:35, o 22:35, użytkownik gord chung <notifications@github.com> napisał:

**Comment by SuderPawel** [comment]
Tests results https://travis-ci.org/gnocchixyz/gnocchi/builds/286672072

First failed test:

```
RuntimeError: Program did not print: `WSGI app 0 \(mountpoint=''\) ready'
Output: *** Starting uWSGI 2.0.15 (64bit) on [Wed Oct 11 19:20:46 2017] ***
compiled with version: 5.4.0 20160609 on 14 September 2017 22:07:01
os: Linux-4.4.0-93-generic #116~14.04.1-Ubuntu SMP Mon Aug 14 16:07:05 UTC 2017
nodename: 1e9cf8a90941
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/tester/src
detected binary path: /home/tester/src/.tox/py27-mysql-ceph-upgrade-from-4.0/bin/uwsgi
chdir() to /tmp/tmpicvdcL
your memory page size is 4096 bytes
detected max file descriptor number: 524288
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (localhost:8041).
bind(): Address already in use [core/socket.c line 769]
```

Second failed test:

```
https://pypi.python.org/packages/d5/d6/f2bf137d71e4f213b575faa9eb426a8775732432edb67588a8ee836ecb80/pbr-3.1.1.tar.gz#md5=4e82c2e07af544c56a5b71c801525b00: [Errno 104] Connection reset by peer
```

**Comment by jd** [comment]
@SuderPawel I'll retry them for you.

**Comment by SuderPawel** [comment]
@jd no rush :smiley: no new tests were added. It is still WIP.

**Comment by SuderPawel** [comment]
Moved to #424.

**Pull request closed without merging**
