### PR TITLE
rest: make sure we use an absolute path for api-paste file

### PR DESCRIPTION
**Pull request by jd**
Add Docker compose support
rest: make sure we use an absolute path for api-paste file

### CODE REVIEW

**Comment by sileht** [comment]
I wonder if this is a good place to put this.
That adds a job that most change will never break.

**Comment by jd** [comment]
Pull-request updated, HEAD is now 2f0ecfe1056ee908d73c196065f6012d47533541

**Comment by jd** [comment]
Pull-request updated, HEAD is now a538ed39ca490c08f1c0742fa8c822d1203d5de6

**Comment by jd** [comment]
@sileht Makes sense. I might build a different repo then.

**Comment by jd** [comment]
Pull-request updated, HEAD is now daf3c67f5547353f65db44b561b8aff005911a90

**Pull request merged**
