### PR TITLE
Merge pep8 and bashate jobs

### PR DESCRIPTION
**Pull request by jd**
That'll simplify the dev workflow and Travis jobs number.

### CODE REVIEW

**Comment by jd** [comment]
Pull-request updated, HEAD is now 19cd783ebf549ecd03f0bdf773175663887c2fee

**Comment by jd** [comment]
Pull-request updated, HEAD is now d2e1382d2e6625d9fe690dac6aae0052361dd9a6

**Comment by jd** [comment]
Pull-request updated, HEAD is now 947b39e308a1eda30f564786fe6e2461ec51d7bf

**Comment by chungg** [comment]
should we just disable bashate job? i noticed it doesn't even fail https://travis-ci.org/gnocchixyz/gnocchi/jobs/241206820

**Comment by jd** [comment]
It fails on error only, those are warning IIUC.

It's only 30s to run and install so I don't really if we keep it, and I don't really care about devstack, so I also don't really care if we don't keep it. :)

**Comment by jd** [comment]
Pull-request updated, HEAD is now 9b2fe128c42f514a3c697d5607eb70bd232c8ef3

**Comment by jd** [comment]
Pull-request updated, HEAD is now b62bc3b20bbd62596d09f2c5878e65bdc4e33487

**Comment by jd** [comment]
Pull-request updated, HEAD is now f9b03a20749db2a3a1135426e9ab2a31f09d4295

**Comment by jd** [comment]
Pull-request updated, HEAD is now 6c9a2f48452f294e6dd14387c424791b7b288f5f

**Comment by jd** [comment]
Pull-request updated, HEAD is now d7f1f0300f64fcea87cf510611dbcb0dc513f5a5

**Pull request merged**
