### PR TITLE
Pin importlib-metadata<3.9.0

### PR DESCRIPTION
**Pull request by tobias-urdin**

### CODE REVIEW

**Comment by tobias-urdin** [comment]
Is this the issue?

**Comment by tobias-urdin** [comment]
@Mergifyio backport stable/4.3 stable/4.4

**Comment by mrunge** [comment]
What is the issue here?

**Comment by tobias-urdin** [comment]
check job result on your patch https://github.com/gnocchixyz/gnocchi/pull/1136 - new release of import-metadata that seems to break stevedore

**Comment by mrunge** [comment]
ah, got you. Thanks!

**Review by mrunge — APPROVED** [review]

**Comment by mrunge** [comment]
Taking a step back: gnocchi does not use importlib-metadata. Not sure if we should declare it then here.

**Comment by tobias-urdin** [comment]
do you have any alternative fix? we can pin stevedore to <3.0.0 but that would conflict with ==3.3.0 upper-constraint for victoria and wallaby release of openstack

**Comment by tobias-urdin** [comment]
maybe block it in tox.ini envs deps instead

**Comment by tobias-urdin** [comment]
fixed in >=3.9.1

**Pull request closed without merging**
