### PR TITLE
Bug Fix -metricd.py

### PR DESCRIPTION
**Pull request by hyunchic86**
mistypo changed

### CODE REVIEW

**Comment by chungg** [comment]
when you update, you should:
- add changed files `git add <file> <file> <file>`
- update commit `git commit --amend`
- push to same PR `git push -f <fork remote name> <branch name>`

you'll need to squash your current commits
- `git rebase -i HEAD~<number of commits to view>`
- edit `pick` to `squash`

**Comment by hyunchic86** [comment]
i will find more issues. i will update it.
@chungg  what is that mean? you didn't find this issue?

**Comment by jd** [comment]
You need to rebase to have a single commit, not 4. see `git-rebase --interactive`.

**Comment by chungg** [comment]
@hyunchic86 i was just wondering why our tests don't see this. but your patch is correct. you just need to rebase and squash your commits into 1

**Comment by jd** [comment]
Closing for https://github.com/gnocchixyz/gnocchi/pull/867

**Pull request closed without merging**
