### PR TITLE
add hint on deployment strategy

### PR DESCRIPTION
**Pull request by chungg**
we can do special deployment if it's a multi-site/region storage

fixes: #60

### CODE REVIEW

**Comment by jd** [comment]
It seems to me the coordinator needs to be reached by the site for some features like `refresh`. Are we sure we want to push that in doc knowing it has drawbacks?

**Comment by chungg** [comment]
yeah, you're right.

we could technically support refresh. but we need to support multiple incoming targets. this means we would need a new option for metricd to grab from multiple incoming i think.

**Comment by chungg** [comment]
so this might actually work. except we need a coordinator and metricd workers per region.

i don't know how we want to satisfy a single coordinated metricd across regions. it' need to be able to connect multiple targets somehow.

**Comment by chungg** [comment]
i'm going to maybe change this to a blog for now

**Pull request closed without merging**
