### PR TITLE
Remove ignore of H216

### PR DESCRIPTION
**Pull request by tobias-urdin**

### CODE REVIEW

**Review by jd — CHANGES_REQUESTED** [review]
too many changes?

**Comment by tobias-urdin** [comment]
was just testing since CI was broken, fixing in other PR

**Comment by tobias-urdin** [comment]
@mergifyio rebase

**Comment by tobias-urdin** [comment]
@mergifyio rebase

**Comment by tobias-urdin** [comment]
@mergifyio backport stable/4.4

**Pull request merged**
