### PR TITLE
Improve indexer and storage INFO logs

### LINKED ISSUE #119: gnocchi-upgrade INFO outputs is barely useful
```
+ gnocchi-upgrade
2017-06-15 12:46:00,338 [8] INFO gnocchi.cli: Upgrading indexer <gnocchi.indexer.sqlalchemy.SQLAlchemyIndexer object at 0x7f2b68768b70>
2017-06-15 12:46:00,548 [8] INFO gnocchi.cli: Upgrading storage <gnocchi.storage.file.FileStorage object at 0x7f2b15e41d30>
```

would be better to have real info. Let's implement a real `__str__` on those storage classes.

### PR DESCRIPTION
**Pull request by BigChief45**
Closes #119 

For some storage drivers I am not really sure what information would be suitable to display in the logs, since I haven't really started using them.

For the indexer and file storage I now get this message:

```
2017-06-16 09:40:05,734 [7284] INFO gnocchi.cli: Upgrading indexer SQLAlchemyIndexer: postgresql://gnocchi:gnocchi@127.0.0.1/gnocchi
2017-06-16 09:40:05,881 [7284] INFO gnocchi.cli: Upgrading storage FileStorage: /home/ubuntu/gn
```

### CODE REVIEW

**Comment by BigChief45** [comment]
@jd Should the tests only check for the presence of `__str__` or also their matching content?

**Comment by jd** [comment]
@BigChief45 Yeah something like that looks good enough. Also rebase/squash, we don't use the merge button anymore, @pastamaker-bot does everything for us once approved, so… :)

**Comment by BigChief45** [comment]
@jd Hm there seems to be an issue at the gate with the connection to the indexer. I will squash once the build passes.

**Comment by jd** [comment]
@BigChief45 The problem should be OK with CI now.

**Comment by BigChief45** [comment]
Something still wrong with the CI. Maybe issues with Docker...?

```
py.error.EACCES: [Permission denied]: mkdir('/home/tester/src/.tox',)
```

**Comment by jd** [comment]
The CI is passing on master but not here and I've no idea why :/

**Pull request merged**
